#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-directory-project
Version  : 31
Release  : 2
URL      : https://github.com/apache/directory-project/archive/31.tar.gz
Source0  : https://github.com/apache/directory-project/archive/31.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/directory/project/project/31/project-31.pom
Source2  : https://repo1.maven.org/maven2/org/apache/directory/project/project/33/project-33.pom
Source3  : https://repo1.maven.org/maven2/org/apache/directory/project/project/34/project-34.pom
Source4  : https://repo1.maven.org/maven2/org/apache/directory/project/project/35/project-35.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-directory-project-data = %{version}-%{release}

%description
This is the trunk for all directory projects.
Branches
--------
directory svn repo base.

%package data
Summary: data components for the mvn-directory-project package.
Group: Data

%description data
data components for the mvn-directory-project package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/project/project/31
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/project/project/31/project-31.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/project/project/33
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/project/project/33/project-33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/project/project/34
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/project/project/34/project-34.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/project/project/35
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/project/project/35/project-35.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/directory/project/project/31/project-31.pom
/usr/share/java/.m2/repository/org/apache/directory/project/project/33/project-33.pom
/usr/share/java/.m2/repository/org/apache/directory/project/project/34/project-34.pom
/usr/share/java/.m2/repository/org/apache/directory/project/project/35/project-35.pom
